name: Deploy Automatizado na EC2

on:
  push:
    branches:
      - main  # Altere para 'master' se a sua branch principal for master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar deploy no EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Estoque-Pro-backend/
            git pull origin main
            docker compose up -d --build
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache